### ISSUE TITLE
Ошибочный шаг

### ISSUE THREAD

**Issue by Texetomg** [jinglescode/time-series-forecasting-tensorflowjs#10]
https://github.com/jinglescode/time-series-forecasting-tensorflowjs/blob/52a2e42277410d119d1d8c86d7deb26661fd2015/index.js#L292

Почему шаг не i+=windowsize?

**Comment by jinglescode** [comment]
In this project, we are using simple moving average, as such the first `window_size` do not have any data per se, we remove them.
