### ISSUE TITLE
Predicting 51st day of stock's close price

### ISSUE THREAD

**Issue by rasulrukhilloev** [jinglescode/time-series-forecasting-tensorflowjs#2]
How exactly are you predicting next day? Can you please refer me to the code which predicts 51st day as shown in the picture you have shared?

**Comment by jinglescode** [comment]
> How exactly are you predicting next day? Can you please refer me to the code which predicts 51st day as shown in the picture you have shared?

In [line 253](https://github.com/jinglescode/time-series-forecasting-tensorflowjs/blob/master/index.js#L253), that is the function that predicts the next value and plots it to the UI. The objective is to feed past N values into the model, to get a prediction. The actual predicting is done at [line 264](https://github.com/jinglescode/time-series-forecasting-tensorflowjs/blob/master/index.js#L264), by calling the [makePredictions](https://github.com/jinglescode/time-series-forecasting-tensorflowjs/blob/master/model.js#L54) function by feeding it with a series of past values (X) and the trained model.

For ploting, note in [line 273](https://github.com/jinglescode/time-series-forecasting-tensorflowjs/blob/master/index.js#L273), it depends if your data is 1 day or 7 days (or any number of days if you are using other data source).
