### ISSUE TITLE
Extending the forecast window

### ISSUE THREAD

**Issue by garagevibes** [jinglescode/time-series-forecasting-tensorflowjs#3]
Hi this is a great guide and i've managed to use it to integrate a bit of forecasting in to a BI tool i was working on so thank you.

I was just wondering if it would be at all possible to feed the result of the prediction back into itself in order to increase the forecast window a week or so.

**Comment by jinglescode** [comment]
Hi @garagevibes, of cause you can. What you have mentioned is one way to do it. If you think about it, all that the model cares about is the input, and it will return you the next value. If you want to get the next 2 values, the easiest way is, like you said, feed the result and predict again, like so:

```
[1,2,3,4] => [5]
[2,3,4,5] => [6]
```
Where `[1,2,3,4]` is your initial values, which predicts `5`. Feed `5` into the input, `[2,3,4,5]` to get the next value.

Note that, if your data is already weekly, then the next value is also weekly.

Another way is, if your work always requires a series of outputs, then that will require to build another type of model. That is called the `sequence to sequence model`. For example, given a series of 50 values, predict the next 7 values.
