### ISSUE TITLE
Using Covid-19 dataset

### ISSUE THREAD

**Issue by KSJaay** [jinglescode/time-series-forecasting-tensorflowjs#8]
So I've taken the time to change the code to use Nodejs instead of the html/js. So when I test with the MSFT dataset I get the expected results, but when I'm testing with a Covid-19 dataset using a very similar method I get loss at around 30. The lowest loss I got was 30 at using 90% for the trainingsize. I also posted a question on StackOverflow to see if I could get some help from there but haven't gotten any help yet. I think I've probably messed something up but I just can't find what.

[Stackoverflow](https://stackoverflow.com/questions/67101549/tensorflow-js-log-loss-high-covid-case-forcasting)

**Comment by jinglescode** [comment]
Hi, I've seen your stackoverflow question. Different datasets will have different losses. `0.01` may look a lot smaller than `36`, but `36` may be very good for that dataset. Test against your test set instead of comparing losses.
